# Generated by Django 4.2.11 on 2024-05-15 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2024, 5, 22)),
        ),
    ]
