# Generated by Django 4.2.11 on 2024-05-17 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0006_orders_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2024, 5, 24)),
        ),
    ]
